// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQlLobm9kd0ynopl5FE_y7FiTNt05WvGM',
    appId: '1:374563387960:web:29d3392924ef4ae41e84cd',
    messagingSenderId: '374563387960',
    projectId: 'vedanidhiv2',
    authDomain: 'vedanidhiv2.firebaseapp.com',
    storageBucket: 'vedanidhiv2.appspot.com',
    measurementId: 'G-9X7NNM12GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNnG9X-QHKzJQpUcYYKCHjSy3xiwV8JwQ',
    appId: '1:374563387960:android:dc1b999458772b4a1e84cd',
    messagingSenderId: '374563387960',
    projectId: 'vedanidhiv2',
    storageBucket: 'vedanidhiv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRCZAkj3h9TcY587JSJ6jUSM7S-tW2F-g',
    appId: '1:374563387960:ios:14a08e4c3fe811251e84cd',
    messagingSenderId: '374563387960',
    projectId: 'vedanidhiv2',
    storageBucket: 'vedanidhiv2.appspot.com',
    iosClientId: '374563387960-51e953gl22igbuog165ip6ahur9g8rk6.apps.googleusercontent.com',
    iosBundleId: 'com.weframe.vedanidhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRCZAkj3h9TcY587JSJ6jUSM7S-tW2F-g',
    appId: '1:374563387960:ios:659a9f29e49f71a91e84cd',
    messagingSenderId: '374563387960',
    projectId: 'vedanidhiv2',
    storageBucket: 'vedanidhiv2.appspot.com',
    iosClientId: '374563387960-51e953gl22igbuog165ip6ahur9g8rk6.apps.googleusercontent.com',
    iosBundleId: 'com.weframe.vedanidhi',
  );
}
