// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/recent_books_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1486678667416097426),
      name: 'RecentBooks',
      lastPropertyId: const IdUid(4, 2620602862401405507),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 180367406742398523),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7261209197976725902),
            name: 'bookName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 366184013694658410),
            name: 'bookId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2620602862401405507),
            name: 'bookImageId',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 1486678667416097426),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    RecentBooks: EntityDefinition<RecentBooks>(
        model: _entities[0],
        toOneRelations: (RecentBooks object) => [],
        toManyRelations: (RecentBooks object) => {},
        getId: (RecentBooks object) => object.id,
        setId: (RecentBooks object, int id) {
          object.id = id;
        },
        objectToFB: (RecentBooks object, fb.Builder fbb) {
          final bookNameOffset = fbb.writeString(object.bookName);
          final bookIdOffset = fbb.writeString(object.bookId);
          final bookImageIdOffset = fbb.writeString(object.bookImageId);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, bookNameOffset);
          fbb.addOffset(2, bookIdOffset);
          fbb.addOffset(3, bookImageIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = RecentBooks(
              bookName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              bookId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              bookImageId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [RecentBooks] entity fields to define ObjectBox queries.
class RecentBooks_ {
  /// see [RecentBooks.id]
  static final id =
      QueryIntegerProperty<RecentBooks>(_entities[0].properties[0]);

  /// see [RecentBooks.bookName]
  static final bookName =
      QueryStringProperty<RecentBooks>(_entities[0].properties[1]);

  /// see [RecentBooks.bookId]
  static final bookId =
      QueryStringProperty<RecentBooks>(_entities[0].properties[2]);

  /// see [RecentBooks.bookImageId]
  static final bookImageId =
      QueryStringProperty<RecentBooks>(_entities[0].properties[3]);
}
